### ISSUE TITLE
Use Pytest instead of Unittest

### ISSUE THREAD

**Issue by xshapira** [Codium-ai/codiumai-vscode-release#1]
Thank you for the excellent vscode extension. CodiumAI rocks! 

But what I hope to see in the next releases is the usage of Pytest instead of Unittest. Pytest has a simpler syntax, offers more robust features, and is more widely used in the community. In addition, it includes the ability to run tests in parallel and the ability to run a subset of tests.

**Comment by DedyKredo** [comment]
@xshapira Thanks for the valuable feedback!
We've changed our default framework to Pytest (instead of Unittest). Unittest is still supported through the "Plan Instructions" section. Let us know if you have any further issues or additional suggestions. Thanks again!
