### ISSUE TITLE
Class final on Java libraries tests example com.azure.cosmos

### ISSUE THREAD

**Issue by LeandriT** [Codium-ai/codiumai-vscode-release#100]
When code has libraries with azure is hard to try to test because it's uses final classes and library doesn't work with this, can you help to test classes final with codiumai please

┆Issue is synchronized with this [Trello card](https://trello.com/c/SHdHMPvQ) by [Unito](https://www.unito.io)

**Comment by sarbjitsinghgrewal** [comment]
### Similar Issues
___

**Comment by sarbjitsinghgrewal** [comment]
### Similar Issues
___

1. **[Test Syntax](https://github.com/Codium-ai/codiumai-vscode-release/issues/76)** (score=0.81)

2. **[Tests not displaying after Codium's latest vscode extension update](https://github.com/Codium-ai/codiumai-vscode-release/issues/7)** (score=0.80)

3. **[CodiumAI, ReactJS with TS](https://github.com/Codium-ai/codiumai-vscode-release/issues/64)** (score=0.80)

4. **["Test this function" is not showing, Also Can't generate testcases.](https://github.com/Codium-ai/codiumai-vscode-release/issues/95)** (score=0.80)

**Comment by almog-lv** [comment]
Hey @LeandriT, thanks for reporting this.
Azure recommends the use of org.mockito.plugins.MockMaker plugin. We suggest you add “use org.mockito.plugins.MockMaker plugin” in the additional instructions field under "Configuration" section, and share whether or not it worked. Or better, if you can create a reproducible public repo, that could help!
Looking forward to hearing from you.
