### ISSUE TITLE
Fix "Sign in to Codium AI" view/title condition 

### ISSUE THREAD

**Issue by kokill** [Codium-ai/codiumai-vscode-release#101]
Currently if user is not logged in "Sign in to Codium AI" is always visible. it should be visible only when `!codium.user.isLoggedIn && view == codium-tree-view `

[Screencast from 2023-10-17 12-15-43.webm](https://github.com/Codium-ai/codiumai-vscode-release/assets/17824552/da6f769b-cc8a-440d-be5c-067f9f420114)

┆Issue is synchronized with this [Trello card](https://trello.com/c/rvV80P69) by [Unito](https://www.unito.io)

**Comment by almog-lv** [comment]
Hey @kokill 
Thanks for reporting this! We are checking this issue and will let you know about the fix.
Can you please mention which IDE you are using? And its version?
Thanks!

**Comment by kokill** [comment]
Here is my VSCode IDE details

```
Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:45:31.402Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.19.0-46-generic snap
```

**Comment by almog-lv** [comment]
@kokill we fixed this bug, it will be released in the next few days, Thanks for reporting!
