### ISSUE TITLE
4/5 code suggestions are empty

### ISSUE THREAD

**Issue by GitMensch** [Codium-ai/codiumai-vscode-release#104]
They do so reasonable but they have an empty base and suggested code

![2 and 3](https://github.com/Codium-ai/codiumai-vscode-release/assets/6699539/45b0f57a-4d8f-48d8-abef-db3dbeb538bb)
![4 and 5](https://github.com/Codium-ai/codiumai-vscode-release/assets/6699539/6c7f06b7-86ce-43fe-8105-7cc8063d01e1)

for the test setup, see #103

**Comment by GitMensch** [comment]
And on second try there are more of those

![new 4 and 5](https://github.com/Codium-ai/codiumai-vscode-release/assets/6699539/722f92df-580b-4b30-bfba-c06e49e60f50)

And the last one is actually wrong, the file is under version control and the installed extension `johnstoncode.svn-scm` is also aware of this.

**Comment by almog-lv** [comment]
Hey @GitMensch can you also attach the request ID of that too? thanks!

**Comment by GitMensch** [comment]
What do you mean here with "not planned"? Are you going to drop the code suggestions altogether? Empty code suggestions obviously don't make any sense...
