### ISSUE TITLE
Generate docstring creates a single big comment string - instead of multiple ones

### ISSUE THREAD

**Issue by GitMensch** [Codium-ai/codiumai-vscode-release#105]
The code explanation is quite good (but in this case this is actually quite easy), but "Generate Docstring" really creates 1 big string, while it would be much more useful to have the summary at the start (where it is), the methods _maybe_ where it is (or separate directly before/after `PROCEDURE DIVISION` header), but to have nearly all variables at the start is not well (much more reasonable to attach it directly before each variable).

for the test setup, see #103

**Comment by almog-lv** [comment]
Hey @GitMensch have you chosen the whole class when you generated the docstring? if yes, that should have worked, maybe it was a bug. The request ID can really help us here too :) thanks!

**Comment by GitMensch** [comment]
Can you please just try that on your side (also on the other issues)? The test setup including the whole source is given at the referenced issue...
