### ISSUE TITLE
tests sound reasonable, but sadly are all in python 

### ISSUE THREAD

**Issue by GitMensch** [Codium-ai/codiumai-vscode-release#106]
For the test setup, see #103

Actually using python may not even be the problem, especially for the external setup - but at least at the `CALL` parts in needs to skip the language barrier (it could start a system process or load the shared object and passing data to it "as in C").

As the checked data is of local scope, the tests would have to be added to the program itself, which would be possible by adding the test stubs as `ENTRY`s, which then can also be called from outside.

**Comment by almog-lv** [comment]
@shaigeva can you help?

**Comment by GitMensch** [comment]
How is that not planned?

README.md says:

* SUPPORTS ALL PROGRAMMING LANGUAGES
* Generate tests using CodiumAI
