### ISSUE TITLE
FR: add an optional argument to /explain to ask about methods/variables

### ISSUE THREAD

**Issue by GitMensch** [Codium-ai/codiumai-vscode-release#107]
Chatting and asking about a variable's / method's use would be nice.

**Comment by almog-lv** [comment]
Hey @GitMensch have you tried it? You can add free text to every command in our Chat.

**Comment by GitMensch** [comment]
I've tried `/explain var-name` and `/explain variable var-name` and only got the summary about the commands; for the test setup, see https://github.com/Codium-ai/codiumai-vscode-release/issues/103

**Comment by almog-lv** [comment]
@mrT23 can you take a look please?

**Comment by mrT23** [comment]
Hi @GitMensch 
the '/explain' command gives a structured explanation for the entire code-under-test.
Following your feedback, we will rename it to '/explain_the_code' to prevent confusion.

We will soon add a different command, '/ask', that can answer any (reasonable :-) ) free text question, like:
`/ask 'explain the variable 'xyz'`
