### ISSUE TITLE
run test angular ts loading without stop failed or success

### ISSUE THREAD

**Issue by aufalmarom** [Codium-ai/codiumai-vscode-release#108]
i'm on researching way to my company with experiment using new project angular 16 and try to generate test case for routing module. it was ok but when run test this tool always loading without stop and alert failed or success. is it true this extension/plugin at vs code or webstorm still beta version? see the attachment file below, thank you.

![image](https://github.com/Codium-ai/codiumai-vscode-release/assets/13025396/8d2296c3-ebf9-473b-b7f3-4f066089ba23)

**Comment by almog-lv** [comment]
@shaigeva please take a look
