### ISSUE TITLE
"Pre-pull request assistant" /commit command doesn't work

### ISSUE THREAD

**Issue by EdenChar** [Codium-ai/codiumai-vscode-release#110]
I can see that the **Pre-pull request assistant** is still available for everyone to try, but I've never been able to make the `/commit` command to work. It would load for hours and never generate any commit message.
Maybe is it only working for premium users ? In which case it would be better to disable it for normal users.

**Comment by almog-lv** [comment]
Hey @EdenChar 
The feature is still available for all users.
Do you have unstaged changes? Is it still loading forever?

**Comment by almog-lv** [comment]
Hey @EdenChar we had an issue with the chat in Windows, we fixed it and released a version yesterday. Can you please update the extension and see if it is fixed?
