### ISSUE TITLE
Bug: Paste in chat broken in Editor Windows with VIM Mode Enabled

### ISSUE THREAD

**Issue by lacostenycoder** [Codium-ai/codiumai-vscode-release#111]
I'm able to cut and paste in chat window in the default sidebar mode, but all cut/paste fails when chat opened in a text editor window.

**Comment by almog-lv** [comment]
@SagiMedina please help

**Comment by almog-lv** [comment]
@lacostenycoder is this issue still happening?

**Comment by lacostenycoder** [comment]
> @lacostenycoder is this issue still happening?

Yes it is, and I seem to have the same issue in the Github Co-Pilot extension as well.

**Comment by almog-lv** [comment]
@lacostenycoder thanks, I am not sure exactly what this bug is, we cannot reproduce it in our side. Do you want to have a quick debugging with us at time that works for you? If yes, please email me - almog.l@codium.ai thanks!
