### ISSUE TITLE
After latest update, Codium no longer works

### ISSUE THREAD

**Issue by photodoc1960** [Codium-ai/codiumai-vscode-release#114]
Sadly it had worked beautifully prior to this last update, with logical options in the left column. Now it is impossible to get it to do anything from that column, and if I highlight code, right click and specify, for example, "explain this code" for a program that is ~50 lines of Python, instead of completing an analysis in seconds it now shows itself as "generating" indefinitely, never completing the task.

**Comment by almog-lv** [comment]
Thank you for reporting @photodoc1960. We are working on fixing this issue and will let you know when it is fixed. sorry for the inconvenience !

**Comment by almog-lv** [comment]
Hey @photodoc1960 can you please send me your email address that you are working with, to my email - almog.l@codium.ai thanks!

**Comment by almog-lv** [comment]
@photodoc1960 this issue was fixed and published to the marketplace, can you please check it again?

**Comment by photodoc1960** [comment]
I’ll check again. As of your prior update, it functioned when the section of code was relatively short, then went on forever if the code were longer in length.

**Comment by acd424** [comment]
I am also getting a continuous "generating" with the latest release (7.14 and 7.13).

When I drop down to 7.10 I get 'There was an issue reading the code in the selected file.' of all my requests.

**Comment by JulsdL** [comment]
I'm facing the same issue. Generating forever, doesn't matter on the context, file of diff. Can't generate a commit message anymore. But for a small function, I could generate a docstring.

**Comment by almog-lv** [comment]
Hello @acd424 @JulsdL and @photodoc1960, would you mind sending me your request IDs so we can investigate it?
You can find it in each received message -> click on the 3 dots and copy the request ID.
Thank you all for reporting this issue and helping us solve it!

**Comment by JulsdL** [comment]
@almog-lv 5194af37-0819-41b0-84b4-a7ea89864dd2

**Comment by JulsdL** [comment]
@almog-lv Sure I'll be happy to help

**Comment by almog-lv** [comment]
@JulsdL, thank you! Please email me at almog.l@codium.ai (your email address is hidden), thanks again :)
