### ISSUE TITLE
Code Suggestions offer incomplete suggestion.

### ISSUE THREAD

**Issue by lnedry** [Codium-ai/codiumai-vscode-release#122]
Request ID: 1984d836-1c8f-48d8-b06d-0440eb1eac26

One of the Code Suggestions suggests using Promise.allSettled instead of Promise.all but the suggested code is incomplete.

It creates an empty array for promises but never inserts anything into that array.

Base Code:
```
// line number: 974
const promises = domains.map(async (domain) => {
    // code omitted for brevity
});

await Promise.all(promises);

```
Suggested Code:
```
const promises = [];
domains.forEach(async (domain) => {
    // code omitted for brevity
});

await Promise.allSettled(promises);

```

**Comment by almog-lv** [comment]
Thanks @lnedry.
@hussam789 take a look please
