### ISSUE TITLE
Unable to execute command

### ISSUE THREAD

**Issue by kaixinol** [Codium-ai/codiumai-vscode-release#124]
Always stuck, no content displayed
![image](https://github.com/Codium-ai/codiumai-vscode-release/assets/100816732/c63e60b4-00f9-4dd6-9b1a-da2e69357dab)

**Comment by almog-lv** [comment]
@kaixinol thanks, can you please click on the "..." button and paste here the request ID?

**Comment by kaixinol** [comment]
This problem has been solved, but I don't know when it was solved.

**Comment by almog-lv** [comment]
We worked on this issue and released a version yesterday, so maybe that fixed it. Thanks @kaixinol !
