### ISSUE TITLE
Internal server error 

### ISSUE THREAD

**Issue by JulsdL** [Codium-ai/codiumai-vscode-release#126]
Codium v0.7.23:

I'm getting this message everytime I try to /describe, /review, /changelog from PR Assistant tab, with "Committed Changes", and /commit with "Staged Changes":

"An internal server error has occurred. Please try again later, and thank you for your patience.[Stopped]"
![image](https://github.com/Codium-ai/codiumai-vscode-release/assets/64731066/9c38ab2b-b947-498f-a92c-1474c9d82db5)

Using Codium extension for VSCode.

Request ID: 88a79a28-a434-4a67-8081-b71dc8068471

**Comment by SagiMedina** [comment]
Hey @JulsdL, can you please try sending a new request? And share the new Request ID here.

**Comment by JulsdL** [comment]
@SagiMedina Hello, I can't reproduce the bug any more. I don't know why it occured. You can close this ticket.

In case you still need it, here's another Request ID: 95809e9f-0555-42f2-9f59-235fea7cff66

**Comment by SagiMedina** [comment]
Great :)
I'll keep it open for a couple of days, if it happens again let me know.

**Comment by JulsdL** [comment]
@SagiMedina Hello ! Internal server error is back. I've been using Codium successfully all the day, and around 16h20 CET, I tried an /improve command on Staged_Changes, wich led to the same error message.

RequestID: 7ea4720f-4e52-42de-815c-5e9a7615cd47

**Comment by almog-lv** [comment]
@JulsdL we saw the issue, @SagiMedina is working on the fix. We will update you once it is released, thanks for reporting!

**Comment by almog-lv** [comment]
@JulsdL we fixed the issue and released a version, please upgrade to latest version and make sure it is working for you
