### ISSUE TITLE
Problem running tests on directories with spaces in their names 

### ISSUE THREAD

**Issue by gustavobittencourt** [Codium-ai/codiumai-vscode-release#127]
First of all, congratulations on this amazing project!

I am having problems running tests in CodiumAI, and I suspect it might be due to my directories having spaces in their names:

```
Command failed: cd /Users/gustavo/Desktop/Gustavo/Projetos/PX Creative Labs/Projetos Internos/Indexação de Documentos/hubie && /Users/gustavo/Desktop/Gustavo/Projetos/PX Creative Labs/Projetos Internos/Indexação de Documentos/venv/bin/python /Users/gustavo/Desktop/Gustavo/Projetos/PX Creative Labs/Projetos Internos/Indexação de Documentos/hubie/codium_86b9694d-83f7-4dbb-9531-6b99e4a7eecb_build_chunk_run.py --path /Users/gustavo/Desktop/Gustavo/Projetos/PX Creative Labs/Projetos Internos/Indexação de Documentos/hubie/codium_86b9694d-83f7-4dbb-9531-6b99e4a7eecb_build_chunk.py
/bin/sh: line 0: cd: /Users/gustavo/Desktop/Gustavo/Projetos/PX: No such file or directory
```

Is there any workaround available to deal with this problem? Renaming the directory would break several other projects I have.

**Comment by givani30** [comment]
I seem to have the same problem when trying to run unit tests:

` Command failed: cd e:\Code\QF Courses\QMIFI_ass2 && c:\Users\givan\anaconda3\envs\pytorch-gpu\python.exe e:\Code\QF Courses\QMIFI_ass2\codium_800ecff2-bd61-4881-a236-b5831f064df9_simbondoption_run.py --path e:\Code\QF Courses\QMIFI_ass2\codium_800ecff2-bd61-4881-a236-b5831f064df9_simbondoption.py
c:\Users\givan\anaconda3\envs\pytorch-gpu\python.exe: can't open file 'e:\\Code\\QF': [Errno 2] No such file or directory
`

**Comment by almog-lv** [comment]
@givani30 @gustavobittencourt thank you both for reporting this!
@OmriGM can you please take a look at these issues?

**Comment by almog-lv** [comment]
@givani30 @gustavobittencourt we are fixing this issue, will let you know when we release the fix. Thanks again for catching it and reporting!

**Comment by gustavobittencourt** [comment]
Thank you!

**Comment by zrusev** [comment]
I had a similar issue and I fixed it by moving my files to another directory with no whitespaces in path's name. Probably the "change directory" command requires a slight modification. Hope this helps.

**Comment by almog-lv** [comment]
@givani30 @gustavobittencourt we fixed the issue and released a version, please upgrade to latest version and make sure it is working for you
