### ISSUE TITLE
PR Assistant says files are deleted 

### ISSUE THREAD

**Issue by AleksandarMilisov** [Codium-ai/codiumai-vscode-release#128]
I tried to test the PR Assistant feature. I have tried several branches with different changes but on every branch the results are the same: coduim says all files are deleted. In turn none of the features for it work /describe, /commit, /review, /changelog

![image](https://github.com/Codium-ai/codiumai-vscode-release/assets/153808100/91f6bba4-9e52-4f03-afc3-cc68b59c53a1)
![image](https://github.com/Codium-ai/codiumai-vscode-release/assets/153808100/28dceae8-46cf-4184-8894-b30862d51855)

**Comment by almog-lv** [comment]
Hey @AleksandarMilisov thanks for reporting. Can you please click on the ... button, copy the request ID and send it to us?

**Comment by AleksandarMilisov** [comment]
I did not save the original one but here is another one that is reproducing it.
Here it is: 873cc74c-d9ef-42ea-a44d-75feeb4cbfd6

This one was made with the very simple repo here:
https://github.com/AleksandarMilisov/Test-Repository/tree/main

**Comment by almog-lv** [comment]
@AleksandarMilisov Thanks; I cloned the repository and couldn't reproduce it. I see that you chose "staged changes" in the context. It means we look at the staged changes against the committed changes in your branch.
Can you please tell me what are your staged changes? And which branch are you working on?

**Comment by AleksandarMilisov** [comment]
Here is another request ID:
ca7b69ce-3259-4a76-8cff-bd5ca7064433

![image](https://github.com/Codium-ai/codiumai-vscode-release/assets/153808100/9a83985c-7e7b-4cb6-9162-beffe8dda77a)

**Comment by almog-lv** [comment]
@AleksandarMilisov thanks, it seems we couldn't read the local file for some reason. We are trying to reproduce this issue and to fix it, we will let you know once it's fixed. Thanks for catching it!

**Comment by almog-lv** [comment]
@AleksandarMilisov we fixed the issue and released a version, please upgrade to latest version and make sure it is working for you

**Comment by AleksandarMilisov** [comment]
It is working for me now, thank you!
