### ISSUE TITLE
This box content overflows outside the box.

### ISSUE THREAD

**Issue by harshalgunjal69** [Codium-ai/codiumai-vscode-release#142]
In codeium ai vscode extension sidebar, when opened, the input box containing placeholder, "Ask anything - use '@' to mention code blocks" has the content overflowing outside the box.

I've attatched the image here:

![Screenshot 2024-02-05 122205](https://github.com/Codium-ai/codiumai-vscode-release/assets/141690905/0c52c813-dfd1-45f5-a830-3c0850e422c2)

**Comment by oranshiner** [comment]
Hey @harshalgunjal69 This is not Codiumate by CodiumAI
