### ISSUE TITLE
Auto Commit Message doesn't work in VS Code.

### ISSUE THREAD

**Issue by danny-su** [Codium-ai/codiumai-vscode-release#144]
<img width="482" alt="image" src="https://github.com/Codium-ai/codiumai-vscode-release/assets/12178855/ad5fd9cf-1205-4d0b-bbba-245f18a7ee06">

**Comment by almog-lv** [comment]
@danny-su thanks for reporting this! This feature is part of the teams plan, so if you're using the free plan it should display a proper error message. We will fix this issue soon. Thanks!

**Comment by danny-su** [comment]
@danny-su I am using the team plan.
<img width="444" alt="image" src="https://github.com/Codium-ai/codiumai-vscode-release/assets/12178855/38d9ab3b-fe8b-488b-bd8e-1ee3c8642c2a">

**Comment by almog-lv** [comment]
Oh I'm sorry. Is the commit message command in the chat working for you?

**Comment by danny-su** [comment]
@almog-lv I didn't find the commit message command in the chat. BTW, the commit message generation of the JetBrains IDE plugin works well.
<img width="368" alt="image" src="https://github.com/Codium-ai/codiumai-vscode-release/assets/12178855/36d10572-c090-41ef-ac46-5f2422b0805e">

**Comment by danny-su** [comment]
@almog-lv By the way, the text "Auto Commit Message" is quite lengthy. Why not use an icon instead?

**Comment by almog-lv** [comment]
@danny-su this bug is being handled and will be fixed soon, thanks!

**Comment by oranshiner** [comment]
Fixed

**Comment by danny-su** [comment]
@oranshiner Not working...
<img width="490" alt="image" src="https://github.com/Codium-ai/codiumai-vscode-release/assets/12178855/71fd3698-6e17-4b9c-bd20-2329a112ce5f">
<img width="1015" alt="image" src="https://github.com/Codium-ai/codiumai-vscode-release/assets/12178855/9899f0ad-ae8f-4184-96ea-0f8a900d9e0f">

**Comment by almog-lv** [comment]
@danny-su do you have stages changes?

**Comment by danny-su** [comment]
@almog-lv Git stages? I don't remember exactly, but both Blackbox AI and GitHub Copilot can generate the commit message successfully.

**Comment by danny-su** [comment]
@almog-lv @oranshiner This function hasn't worked until now, even if I just changed a line of code.

<img width="637" alt="56861" src="https://github.com/Codium-ai/codiumai-vscode-release/assets/12178855/5c93ed0c-c873-452a-a0ac-3d176ba4ac3b">
