### ISSUE TITLE
Extend Test Suite buttons don't work

### ISSUE THREAD

**Issue by tanc** [Codium-ai/codiumai-vscode-release#145]
The buttons in the Extend Test Suite tab don't do anything when clicked on. There are lots of tests listed under Happy Path and Edge Cases with "Go to test" or "Generate test" buttons. Clicking on them does nothing at all. Is this because I'm on the free trial or is something broken? I would expect to have the functionality while in the trial period.

https://github.com/Codium-ai/codiumai-vscode-release/assets/76320/a295f2e7-fd98-49db-b948-6b7e07b7e166

**Comment by almog-lv** [comment]
Hey @tanc while you are on trial, you can use all the functionality of the paid version. In your video I see you click on the generate test and go to test buttons, and nothing happens. It seems like a bug. Do you have tests below the behaviors list?
