### ISSUE TITLE
Bug: [Codiumate Chat] Showing Incorrect selected line numbers

### ISSUE THREAD

**Issue by srinua542** [Codium-ai/codiumai-vscode-release#147]
In the provided screenshot, I've highlighted lines 117-122, yet the user chat message container displays 116-121.

![image](https://github.com/Codium-ai/codiumai-vscode-release/assets/99633982/f51fc847-35e7-4da5-a287-bdb68bc26558)

**Comment by oranshiner** [comment]
Thank you for reporting this bug, we fixed it in version 0.7.47
