### ISSUE TITLE
Feat: [Coduimate Chat] On mouse over commands suggestion in input make the cursor to pointer from default

### ISSUE THREAD

**Issue by srinua542** [Codium-ai/codiumai-vscode-release#148]
When entering text in the Coduimate chat, a command suggestions popup appears. Hovering over any of the commands causes the mouse cursor change to text selector, make it as `pointer` so that it indicate that the command item is clickable.

![image](https://github.com/Codium-ai/codiumai-vscode-release/assets/99633982/34871718-2418-4b85-a0c9-e0b41285fea0)

**Comment by oranshiner** [comment]
Fixed
