### ISSUE TITLE
No spaces in input fielt "General instructions"

### ISSUE THREAD

**Issue by eikowagenknecht** [Codium-ai/codiumai-vscode-release#151]
Why can't I type in spaces here?

![image](https://github.com/Codium-ai/codiumai-vscode-release/assets/1475672/af1ca273-c978-4ab2-9d6e-48dad9829d3a)

Selecting from "Hints" can do it, though, so the problem is only on user input.

**Comment by almog-lv** [comment]
@OmriGM please take a look

**Comment by oranshiner** [comment]
@eikowagenknecht Thank you for reporting this issue, we fixed it, please upgrade to the latest version
