### ISSUE TITLE
Codiumate chat issue

### ISSUE THREAD

**Issue by dnylnd** [Codium-ai/codiumai-vscode-release#152]
im using Codiumate in VS Code. i logged in and the ai chat is not working.
it generates the answer forever. yestarday it worked perfectly.

**Comment by oranshiner** [comment]
@dnylnd Hey, Thank you for reporting this issue. Please add the request-id or your email so we can find the issue. You can send your email directly to me at oran.s@codium.ai or support@codium.ai
![image](https://github.com/Codium-ai/codiumai-vscode-release/assets/42638110/6ef4a6a9-16af-479d-9e35-8df1abbdb108)

**Comment by davidadjele** [comment]
Hi, I think i have the same issue.

Error:
`We were unable to process the request 02b6ca7f-d11e-4f98-bf3f-2ba88301dce1:f022e1f8-fea9-41df-8b82-1dc89be44ccc`

**Comment by oranshiner** [comment]
Hey, if this issue still reproducible please re-open the ticket and share a request-id
