### ISSUE TITLE
Blocks switching between windows on Mac

### ISSUE THREAD

**Issue by XOP** [Codium-ai/codiumai-vscode-release#153]
It seems that some recent update has changed something in the native windows switching.  

Usually you would switch windows on Mac via standard shortcut `Cmd+``.   
It is very noticeable after VS Code restart that this functionality works until extensions are loaded. 
Once loaded, it does not work anymore. I disabled / enabled extensions until finally reached Codiumate.

When disabled and enabled for a selected workspace the issues is gone.  
However when enabled for at least 2 workspaces, issues comes back.

**Comment by oranshiner** [comment]
Thank you for reporting the issue. We will check it and fix it as soon as possible

**Comment by oranshiner** [comment]
Hey, 
We don't use the Cmd+ shortcut, try looking at the default keyboard shortcuts by pressing Cmd+Shift+P and see who use it
![image](https://github.com/Codium-ai/codiumai-vscode-release/assets/42638110/a8b16de4-72cf-48bd-9205-c48f03130492)
