### ISSUE TITLE
Auto Commit Generates Default Message with .gitignore Staged

### ISSUE THREAD

**Issue by ilchemla** [Codium-ai/codiumai-vscode-release#154]
### Problem:

When I use "Auto Commit" in the VSCode GenAI extension and have a .gitignore file staged, I keep getting the same commit message every time:

```bash
Updated func1 in src/file1.py and made minor changes in src/file2.py
```

This doesn't match what I actually changed. It's like it ignores my real changes and just sticks to this default message.

### Steps to Reproduce:

1. Stage changes including a .gitignore file.
2. Hit "Auto Commit".
3. See the same default commit message pop up.

### What Should Happen:

The commit message should actually say what was changed, not just throw out a default message that has nothing to do with my work.

### What Does Happen:

I get a canned message about updating func1 in src/file1.py and tweaks in src/file2.py no matter what the real changes are.

### Why This Sucks:

It's confusing and messes up the commit history, making it hard to track real changes.

### Debugging Info:

```
20a7c03c-e552-43f1-9b69-c414632ddb6a
```

### Setup:

VSCode version: 1.87.1
Codium-Mate Extension version: v0.7.49

<img width="428" alt="image" src="https://github.com/Codium-ai/codiumai-vscode-release/assets/16705918/6183d95e-09a8-4028-b545-33c25d1161f3">

**Comment by oranshiner** [comment]
Fixed
