### ISSUE TITLE
codiumai: We were unable to process the request 263ae441-aac8-4b44-9dc6-86d38cb52275

### ISSUE THREAD

**Issue by Luluam** [Codium-ai/codiumai-vscode-release#157]
Hi, when I'm using the option 'continue this chat' after the second question that I ask it have being unable to answer answer and drop me the error: We were unable to process the request 263ae441-aac8-4b44-9dc6-86d38cb52275
[c:\Users\user\Documents\DC_Lar\Doce_Lar\models.py](vscode://file/c:\Users\user\Documents\DC_Lar\Doce_Lar\models.py)
[4/4/2024, 2:02:10 AM]
[Stopped]
All in red color. However the continue this chat was working normally yesterday then today it is giving me this error

**Comment by oranshiner** [comment]
Hey @Luluam Thank you, we are working on a fix for this issue, i would let you know when its fixed

**Comment by oranshiner** [comment]
Fixed in version 0.8.3, Thank you
