### ISSUE TITLE
unable to continue chats after two chats on choosing  'continue this chat'.  request 67eb9c87-e189-4ffc-844c-3bda2e6f2f18

### ISSUE THREAD

**Issue by FluffyRudy** [Codium-ai/codiumai-vscode-release#158]
when i press continue this chat and make two more chats it gives
_**We were unable to process the request 67eb9c87-e189-4ffc-844c-3bda2e6f2f18**_

**Comment by oranshiner** [comment]
Duplicate as issue #157

**Comment by FluffyRudy** [comment]
![image](https://github.com/Codium-ai/codiumai-vscode-release/assets/81473138/ed03a228-88fa-490e-8d30-91868852fa33)
@oranshiner look at this

**Comment by oranshiner** [comment]
Yes, I know. I wrote it a duplicate as another open issue that was open before this one, I'm sorry about the confusion
We will release a version that its fixed tomorrow and close the other issue as well.

**Comment by oranshiner** [comment]
Fixed in version 0.8.3, Thank you
