### ISSUE TITLE
Unable to log in, stucking at the Sign in message

### ISSUE THREAD

**Issue by chxzqw** [Codium-ai/codiumai-vscode-release#185]
![image](https://github.com/user-attachments/assets/1de430d5-30ef-412c-a0ee-580c3fd6afeb)
Please see the above screenshot, there is no any pop up window/hint something. I had already logged in Codeium account through Chrome. No idea what am I missing here.

**Comment by almog-lv** [comment]
Hello, this is a different extetion. We are Qodo Gen, not Codeium
