### ISSUE TITLE
Replace 'generate tests' button with keybinding

### ISSUE THREAD

**Issue by xshapira** [Codium-ai/codiumai-vscode-release#3]
Remove the `generate tests` button above the Python class or function and use keybind reference instead. Suggested keybinding: `Option + T` on Mac.

┆Issue is synchronized with this [Trello card](https://trello.com/c/97KCVkSS) by [Unito](https://www.unito.io)

**Comment by DedyKredo** [comment]
Thanks @xshapira for the feedback! Is there a specific reason why you think we should remove the button?

**Comment by xshapira** [comment]
To ensure uninterrupted focus while debugging or even coding, let the user have the option to disable the button but still have access via the keybinding.
