### ISSUE TITLE
Support for Dart

### ISSUE THREAD

**Issue by hortigado** [Codium-ai/codiumai-vscode-release#61]
Hello, is there any plan to support dart? good project

┆Issue is synchronized with this [Trello card](https://trello.com/c/o21Dd5mi) by [Unito](https://www.unito.io)

**Comment by almog-lv** [comment]
Thank you @hortigado , we are planning to support more languages during this year, probably in the second half of 2023. Dart is in our list, we are publishing news in our [Discord community](https://discord.gg/kG35uSHDBc) and in our [newsletter](https://www.codium.ai/#home-wait), so stay tuned :)
