### ISSUE TITLE
CodiumAI, ReactJS with TS

### ISSUE THREAD

**Issue by JosepSalvat** [Codium-ai/codiumai-vscode-release#64]
Is it supported? Because for some reason doesn't work for me :/

┆Issue is synchronized with this [Trello card](https://trello.com/c/JVEOjv9f) by [Unito](https://www.unito.io)

**Comment by JosepSalvat** [comment]
Hello, I can't access to codium.ai. When I go to the Codium.ai Tab it says:

Could not find any components to test. And it's a Functional component build with typsecript. .*tsx

**Comment by SagiMedina** [comment]
Hi @JosepSalvat 

Thank you for reaching out and reporting the issue you encountered with CodiumAI in React functions. As of now, our tool is designed to support native JavaScript and TypeScript functions and classes, as well as Python functions and classes.

We appreciate your interest in React support, and we're excited to inform you that supporting React functions is on our roadmap. In fact, our team is actively working on this feature to extend our product's capabilities to better serve users like you.

As it is a work in progress, I cannot provide you with a specific release date at this moment. However, I encourage you to keep an eye on our GitHub page for updates and the eventual release of this feature. You can also subscribe to the repository to receive notifications about new releases and updates.

If you have any further questions or suggestions, please don't hesitate to get in touch. We value the input and expertise of our community members.

**Comment by JosepSalvat** [comment]
Cool! Thanks! Looking forward to test it when its ready :D
