### ISSUE TITLE
Can't Login on WSL: Ubuntu

### ISSUE THREAD

**Issue by arsistyle** [Codium-ai/codiumai-vscode-release#65]
Im using WSL: Ubuntu on WIndows 11

This happens in the WSL remote view, but if I do it in a normal window I can login.

![image](https://user-images.githubusercontent.com/7788144/232603029-cccaa304-2c66-46f9-a4c0-36545c768729.png)

![image](https://user-images.githubusercontent.com/7788144/232603081-2176a602-0285-43a4-8a11-0e4d53efcb3c.png)
*  ( i ) This extension is enabled on the remote extension host because it prefers to run there.

┆Issue is synchronized with this [Trello card](https://trello.com/c/tsbVp4dK) by [Unito](https://www.unito.io)

**Comment by arsistyle** [comment]
Today it worked and I did nothing, I will close this problem.

**Comment by almog-lv** [comment]
Thanks @arsistyle !
