### ISSUE TITLE
AVA support?

### ISSUE THREAD

**Issue by MarcinWArdentCode** [Codium-ai/codiumai-vscode-release#66]
Would love to see [AVA](https://github.com/avajs/ava) supported.

┆Issue is synchronized with this [Trello card](https://trello.com/c/ZEt5PNhi) by [Unito](https://www.unito.io)

**Comment by mrT23** [comment]
Hi @MarcinWArdentCode 
we support a wide variety of testing frameworks and runners. Even for frameworks that are not listed in the 'global settings', you can use the 'General instructions' and 'Chat' tabs to enable them.
see for example:
https://discord.com/channels/1057273017547378788/1057273018084237344/1097465657425149992


However, from what I see here:
https://github.com/avajs/ava
AVA only supports test("...") style, and not it("...") style. (correct me if am wrong).
So i think for that reason we cannot support it at the moment
