### ISSUE TITLE
not support python's unit test genneration?

### ISSUE THREAD

**Issue by bolt163** [Codium-ai/codiumai-vscode-release#67]
actually not support python's unit test genneration?

┆Issue is synchronized with this [Trello card](https://trello.com/c/u6RAisgd) by [Unito](https://www.unito.io)

**Comment by almog-lv** [comment]
Hello, are you working on the VSCode extension? If yes - you can change the framework to "unittest" instead of "pytest" in the settings, attaching the documentation about testing configuration - https://github.com/Codium-ai/codiumai-vscode-release#change-test-suite-configurations 
Let us know if it worked for you. Thanks!

**Comment by bolt163** [comment]
> Hello, are you working on the VSCode extension? If yes - you can change the framework to "unittest" instead of "pytest" in the settings, attaching the documentation about testing configuration - https://github.com/Codium-ai/codiumai-vscode-release#change-test-suite-configurations Let us know if it worked for you. Thanks!

the operation path is so deep that somebody  nearly cant find it , and the unittest/pytest switch pannel  seems not be  seen to users ....

**Comment by almog-lv** [comment]
@bolt163 it looks like you are working on a file that starts with "test" and CodiumAI filters these type of files (since they are most of the times test files, and we don't generate tests for test functions). Try to rename the file and it should work.

**Comment by bolt163** [comment]
> @bolt163 it looks like you are working on a file that starts with "test" and CodiumAI filters these type of files (since they are most of the times test files, and we don't generate tests for test functions). Try to rename the file and it should work.

it's not the name contains tests function...

**Comment by bolt163** [comment]
> The name of the file is testClass.py and CodiumAI filters these files, if you change the name to something else (let's say "wallet.py") it should work

not working...
![企业微信截图_16819029899100](https://user-images.githubusercontent.com/25170435/233058286-255d2548-05f4-46bd-a519-030d30b638bd.png)

**Comment by oranshiner** [comment]
Hello, 
I would like to check your case on our logs and for that, I need the email with which you signed up for Codium, could you please send it to oran.s@codium.ai, also please send me a picture of the screen that you see on the low right side so I can see what color the Codium icon is.
![image](https://user-images.githubusercontent.com/42638110/233063484-ff3cce45-f26d-440d-aa8d-bb27e43e2691.png)

thank you, 
Oran.

**Comment by bolt163** [comment]
> Hello, I would like to check your case on our logs and for that, I need the email with which you signed up for Codium, could you please send it to [oran.s@codium.ai](mailto:oran.s@codium.ai), also please send me a picture of the screen that you see on the low right side so I can see what color the Codium icon is. ![image](https://user-images.githubusercontent.com/42638110/233063484-ff3cce45-f26d-440d-aa8d-bb27e43e2691.png)
> 
> thank you, Oran.

no thanks...the operation is so crazy to me, i don't need it now
