### ISSUE TITLE
Typescript find anonymous components

### ISSUE THREAD

**Issue by bohrium2b** [Codium-ai/codiumai-vscode-release#68]
## The problem
Codium-ai does not detect components in typescript that are defined using the 
```tsx
const ComponentName: React.FC = () => { ... }
```
to test.

My code:
```tsx
... imports ...

const Hello: React.FC = () => {
  const [name, setName] = useState('')
  const message = name === '' ? 'world' : name
  return (<><TextField type="text" value={name} onChange={(event) => {
    setName(event.target.value)
  }}/>
    <Typography>Hello, {message}</Typography>
  </>

  )
}
... Stuff ...
```
Codium output: 
![image](https://user-images.githubusercontent.com/85321730/234119852-014af3ee-e004-4992-a28d-147e95c798af.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/FEFqXpfj) by [Unito](https://www.unito.io)

**Comment by almog-lv** [comment]
Hey @bohrium2b  we have released a new version (>0.5.22), now you can select the code, right-click on it and choose the "CodiumAI - Generate Test" button. It should support your case. Let us know if it works for you! Thanks.
See how it works - https://youtu.be/fEZsdLPRp5k
