### ISSUE TITLE
It doesn't recognise functional components without a return

### ISSUE THREAD

**Issue by eddy20vt** [Codium-ai/codiumai-vscode-release#69]
Hi, I have a component like...

`const Tooltip = ({ alwaysVisible, className, id, noArrow, ...props }) => (
  <BSTooltip
...
 />
);
`

instead of:
`const Tooltip = ({ alwaysVisible, className, id, noArrow, ...props }) => {
return (
  <BSTooltip
...
 />
)
}
`

The extension is able to recognise the second implementation... but not the first one.
It shows the message: _Could not find any component to test_

My implementation way is very extended when you don't need to use constants, functions or whatever other declarations and you can return directly an object.

Thanks!
Best, Edu

┆Issue is synchronized with this [Trello card](https://trello.com/c/HHPhRT9o) by [Unito](https://www.unito.io)

**Comment by almog-lv** [comment]
Hey @eddy20vt we have released a new version (>0.5.22), now you can select the code, right-click on it and choose the "CodiumAI - Generate Test" button. It should support your case. Let us know if it works for you! Thanks.
See how it works - https://youtu.be/fEZsdLPRp5k
