### ISSUE TITLE
It's not possible to type the grave accent

### ISSUE THREAD

**Issue by edotassi** [Codium-ai/codiumai-vscode-release#71]
With Codeium Vs Code extension activated i can't type grave accent in the editor.

VsCode info:

Version: 1.78.0 (Universal)
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:11:00.813Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: No

Codeium Extension: [1.2.13] - 2023-05-03

Italian layout

┆Issue is synchronized with this [Trello card](https://trello.com/c/UwjkLhlC) by [Unito](https://www.unito.io)

**Comment by almog-lv** [comment]
Hello, Codeium is a different extension, not maintained by CodiumAI.
