### ISSUE TITLE
unable to sign in it with GitHub.

### ISSUE THREAD

**Issue by zm0688-cn** [Codium-ai/codiumai-vscode-release#73]
Type: <b>Bug</b>

it open vscode other wise Cursor.

Extension version:Codium.AI 0.5.26
VS Code version: Cursor 0.2.11 (089994861982da4f5555ef3f09d044ae1b16f997, 2023-05-09T09:12:52.091Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

┆Issue is synchronized with this [Trello card](https://trello.com/c/21uFwq4e) by [Unito](https://www.unito.io)

**Comment by zm0688-cn** [comment]
"Cursor" is a .exe from https://www.cursor.so/

**Comment by almog-lv** [comment]
Hello, @zm0688-cn. Is this issue still happening?
