### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by arvindan1308** [Codium-ai/codiumai-vscode-release#74]
Hi, just wanted to ask whether we can use this with CI CD pipeline or not?

┆Issue is synchronized with this [Trello card](https://trello.com/c/cBAnfeyB) by [Unito](https://www.unito.io)

**Comment by almog-lv** [comment]
Hey, @arvindan1308 thanks for your question.
Currently no, but it is planned to be supported in the future
Stay tuned
