### ISSUE TITLE
The app can't run any test. 

### ISSUE THREAD

**Issue by socampo13** [Codium-ai/codiumai-vscode-release#75]
Each time I want to run a test it is giving me an error, showing me a huge path that has no sense to me. It is not possible to change the path or see a way to fix it.

┆Issue is synchronized with this [Trello card](https://trello.com/c/pJ1BAzG0) by [Unito](https://www.unito.io)

**Comment by almog-lv** [comment]
Thank you, @socampo13. We improved the clarity of the failures; you should have a more explicit error message now (please install the latest version). Let me know if you still need help with that. Thanks!
