### ISSUE TITLE
Test Syntax

### ISSUE THREAD

**Issue by tegmos** [Codium-ai/codiumai-vscode-release#76]
Hi! Awesome tool so far!  

Question regarding the syntax - all tests currently use `it` to define the tests. We've been using `test` and would like to make it all consistent, but I can't figure out how to tell Codium to do so.  I tried giving an example test and adding "Use 'test' over 'it'." (or similar wording) in the hints, but it always still uses "it".

Minor annoyance, but trying to figure out how to fine-tune if for our style.

Thanks!

┆Issue is synchronized with this [Trello card](https://trello.com/c/uJeWgtzL) by [Unito](https://www.unito.io)

**Comment by mrT23** [comment]
Hi @tegmos 

Currently we support only "it", and you cannot change it via the hints. 

We appreciate your feedback, and we will consider in the future supporting also the "test" format

Thanks,
Tal
