### ISSUE TITLE
Cannot sign in with VSCode Insiders

### ISSUE THREAD

**Issue by sh786** [Codium-ai/codiumai-vscode-release#80]
After installing the extension in VSCode Insiders, when I try to sign in, the redirect after sign in only opens VSCode (standard version), and does not respect that the sign in was triggered from VSCode Insiders

┆Issue is synchronized with this [Trello card](https://trello.com/c/WczL82EY) by [Unito](https://www.unito.io)

**Comment by FlatMapIO** [comment]
I only installed vscode-insiders, still unable to login.

**Comment by iloving** [comment]
Not just insiders.  I'm using regular visual studio code 1.79.2 from homebrew and I can't log in either.

**Comment by almog-lv** [comment]
@sh786 @FlatMapIO please upgrade to latest version, it is now supported
