### ISSUE TITLE
Code suggestion do not work

### ISSUE THREAD

**Issue by datenreisender** [Codium-ai/codiumai-vscode-release#94]
I do not get automatic code suggestions.

I tried the typical Python `def fib(n):` example and nothing happens. When I use the “Get Code Suggestion” command, I get this error:

![image](https://github.com/Codium-ai/codiumai-vscode-release/assets/260705/47eb0dda-07e4-46d8-a50f-2a4ce0c9a0d5)

I _am_ logged in correctly though and if I click on “Test this function” and in the new pane on “Code Suggestions” I do get a helpful suggestion. Having always to go there is just a lot too cumbersome to use this all the time.

┆Issue is synchronized with this [Trello card](https://trello.com/c/Ne6kR09a) by [Unito](https://www.unito.io)

**Comment by f-lawe** [comment]
Same error here, running VS Code on Windows 11.

**Comment by almog-lv** [comment]
@OmriGM can you look at that, please?

**Comment by OmriGM** [comment]
Hey @datenreisender @f-lawe , 
We'll fix this bug, for now, here are two temporal solutions to help you get code suggestions for selected code:

Select the code you want to get suggestions for -> Right click --> Click CodiumAI -> Click "Get code suggestions" 
![image](https://github.com/Codium-ai/codiumai-vscode-release/assets/24547476/c2c8736b-f08e-418e-ae55-41599bcf8aa8)

Or, use the other "Get code suggestions" command.
![image](https://github.com/Codium-ai/codiumai-vscode-release/assets/24547476/332f83a0-c812-4c94-a717-e5d28cb226a8)
