### ISSUE TITLE
"Test this function" is not showing, Also Can't generate testcases.

### ISSUE THREAD

**Issue by vigneshgtp** [Codium-ai/codiumai-vscode-release#95]
<img width="711" alt="Screenshot_3" src="https://github.com/Codium-ai/codiumai-vscode-release/assets/141414898/4946d749-32d5-4937-8dc3-f7bea47f075f">

Since last night i am unable to generate test cases for a defined function or a class.
Quick action for generating test cases is not working. Even if i click Refresh icon Nothing happens!!

┆Issue is synchronized with this [Trello card](https://trello.com/c/R67w7NkZ) by [Unito](https://www.unito.io)

**Comment by almog-lv** [comment]
@shaigeva can you take a look please?

**Comment by almog-lv** [comment]
Hey @vigneshgtp is this issue still happening?
